interface SeedProduct {
  name:           string;
  category:       string;
  sub_category:   string;
  price:          number;
  image_url:      string;
  product_url:    string;
  is_active:      boolean;
  is_top_tier?:   boolean;
  is_budget_king?: boolean;
  description?:   string;
}

function calcPrice(cost: number): number {
  return Math.round((cost * 1.20 + 3.99) * 100) / 100;
}

function amz(asin: string): string {
  return `https://www.amazon.it/dp/${asin}?tag=kitwer26-21`;
}

function ph(cat: string): string {
  const slugs: Record<string, string> = {
    'FPV Drones':     'fpv-drones',
    'Sim Racing':     'sim-racing',
    'Crypto Wallets': 'crypto-wallets',
    'Cyber Security': 'cyber-security',
  };
  return `/images/categories/${slugs[cat] ?? 'generic'}-placeholder.jpg`;
}

const FPV_DRONES: SeedProduct[] = [
  // RTF Kits
  {
    name: 'DJI O3 Air Unit — Video Transmission System',
    category: 'FPV Drones', sub_category: 'vtx-cameras',
    price: calcPrice(149),
    image_url: 'https://m.media-amazon.com/images/I/61+oRDmMShL._AC_SL1500_.jpg',
    product_url: amz('B09MGMZJ5L'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Caddx Nebula Pro Nano Kit — FPV Camera DJI',
    category: 'FPV Drones', sub_category: 'vtx-cameras',
    price: calcPrice(89),
    image_url: 'https://m.media-amazon.com/images/I/71cJbEnB3xL._AC_SL1500_.jpg',
    product_url: amz('B094T8GF5Y'),
    is_active: true,
  },
  {
    name: 'GEPRC Cinelog25 HD — Cinewhoop 2.5" FPV Drone',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(199),
    image_url: 'https://m.media-amazon.com/images/I/71r0rioAJPL._AC_SL1500_.jpg',
    product_url: amz('B09WZK2NK1'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'BetaFPV Pavo25 Whoop — Cinewhoop 2.5" BNF',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(159),
    image_url: ph('FPV Drones'),
    product_url: amz('B09H4RHKGB'),
    is_active: true,
  },
  {
    name: 'iFlight Nazgul Evoque F5D V2 — 5" FPV Freestyle Drone',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(279),
    image_url: 'https://m.media-amazon.com/images/I/71kzYqK8W5L._AC_SL1500_.jpg',
    product_url: amz('B0BJHF2CLQ'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Foxeer Razer Mini — FPV Racing Camera 1200TVL',
    category: 'FPV Drones', sub_category: 'vtx-cameras',
    price: calcPrice(35),
    image_url: 'https://m.media-amazon.com/images/I/61Qm7DPy8OL._AC_SL1500_.jpg',
    product_url: amz('B07QRNFHCB'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'EMAX Tinyhawk III Plus — RTF FPV Drone Kit con Occhiali',
    category: 'FPV Drones', sub_category: 'rtf-kits',
    price: calcPrice(119),
    image_url: 'https://m.media-amazon.com/images/I/71FPCFnP-QL._AC_SL1500_.jpg',
    product_url: amz('B0B1HKCNCM'),
    is_active: true,
  },
  {
    name: 'Diatone Roma F35 — 3.5" FPV Cinewhoop',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(179),
    image_url: ph('FPV Drones'),
    product_url: amz('B0BSJK9K5Z'),
    is_active: true,
  },
  // Motors
  {
    name: 'EMAX RS2306 — Brushless Motor 2400KV FPV Racing',
    category: 'FPV Drones', sub_category: 'motors',
    price: calcPrice(22),
    image_url: 'https://m.media-amazon.com/images/I/51jlP4b7UEL._AC_SL1000_.jpg',
    product_url: amz('B07D5G5YW7'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'T-Motor F40 PRO IV — 2400KV Racing Motor',
    category: 'FPV Drones', sub_category: 'motors',
    price: calcPrice(29),
    image_url: ph('FPV Drones'),
    product_url: amz('B07VHVDXVH'),
    is_active: true,
  },
  {
    name: 'iFlight XING2 2207 — 1855KV Motor FPV 5"',
    category: 'FPV Drones', sub_category: 'motors',
    price: calcPrice(25),
    image_url: 'https://m.media-amazon.com/images/I/61CqxKbFGPL._AC_SL1500_.jpg',
    product_url: amz('B093MXNYZQ'),
    is_active: true,
  },
  // ESC & Stack
  {
    name: 'Holybro Kakute H7 V2 + Atlatl HV — FC+VTX Stack',
    category: 'FPV Drones', sub_category: 'general',
    price: calcPrice(95),
    image_url: ph('FPV Drones'),
    product_url: amz('B09KQRL7FQ'),
    is_active: true,
  },
  {
    name: 'Diatone Mamba F405 MK3 — F4 FC Stack 45A 4in1 ESC',
    category: 'FPV Drones', sub_category: 'general',
    price: calcPrice(75),
    image_url: ph('FPV Drones'),
    product_url: amz('B07WPC4GD3'),
    is_active: true,
  },
  {
    name: 'BetaFPV F4 2-4S Whoop — FC AIO ESC Stack',
    category: 'FPV Drones', sub_category: 'general',
    price: calcPrice(48),
    image_url: ph('FPV Drones'),
    product_url: amz('B09FDRTDXZ'),
    is_active: true, is_budget_king: true,
  },
  // Frames
  {
    name: 'TBS Source One V5 — 5" Open Source FPV Frame',
    category: 'FPV Drones', sub_category: 'frames',
    price: calcPrice(28),
    image_url: 'https://m.media-amazon.com/images/I/71JFv4Qq4QL._AC_SL1500_.jpg',
    product_url: amz('B09CQTPK4B'),
    is_active: true,
  },
  {
    name: 'iFlight Chimera7 Pro V2 — 7" Long Range FPV Frame',
    category: 'FPV Drones', sub_category: 'frames',
    price: calcPrice(65),
    image_url: ph('FPV Drones'),
    product_url: amz('B0BQSH1R42'),
    is_active: true,
  },
  // Goggles
  {
    name: 'DJI Goggles 2 — FPV HD Video Googles',
    category: 'FPV Drones', sub_category: 'fpv-goggles',
    price: calcPrice(489),
    image_url: 'https://m.media-amazon.com/images/I/71C5XfZS4IL._AC_SL1500_.jpg',
    product_url: amz('B0BG26LTMB'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Fatshark Dominator HD3 — HD FPV Goggles',
    category: 'FPV Drones', sub_category: 'fpv-goggles',
    price: calcPrice(299),
    image_url: ph('FPV Drones'),
    product_url: amz('B07K7GV45S'),
    is_active: true,
  },
  {
    name: 'SKYZONE SKY04X PRO — OLED FPV Goggles 1280x960',
    category: 'FPV Drones', sub_category: 'fpv-goggles',
    price: calcPrice(349),
    image_url: ph('FPV Drones'),
    product_url: amz('B09Y3WT8L9'),
    is_active: true,
  },
  // Radios
  {
    name: 'RadioMaster Boxer ELRS — EdgeTX RC Controller',
    category: 'FPV Drones', sub_category: 'radios-elrs',
    price: calcPrice(119),
    image_url: 'https://m.media-amazon.com/images/I/71zP-VFqC5L._AC_SL1500_.jpg',
    product_url: amz('B0BPYQXKH2'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'BetaFPV LiteRadio 3 Pro — ELRS 2.4GHz Controller',
    category: 'FPV Drones', sub_category: 'radios-elrs',
    price: calcPrice(55),
    image_url: ph('FPV Drones'),
    product_url: amz('B0BG3D4GCH'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'RadioMaster TX16S MKII — Hall Gimbals EdgeTX',
    category: 'FPV Drones', sub_category: 'radios-elrs',
    price: calcPrice(149),
    image_url: ph('FPV Drones'),
    product_url: amz('B09H6ST3VT'),
    is_active: true,
  },
  // Batteries & Chargers
  {
    name: 'Tattu R-Line V3.0 — 6S 1550mAh 120C LiPo',
    category: 'FPV Drones', sub_category: 'batteries-chargers',
    price: calcPrice(39),
    image_url: 'https://m.media-amazon.com/images/I/71XLBFwDDhL._AC_SL1500_.jpg',
    product_url: amz('B08HNXHCFJ'),
    is_active: true,
  },
  {
    name: 'ISDT Q6 Pro — LiPo Charger 14A 300W',
    category: 'FPV Drones', sub_category: 'batteries-chargers',
    price: calcPrice(55),
    image_url: ph('FPV Drones'),
    product_url: amz('B074BDYFP8'),
    is_active: true,
  },
  {
    name: 'VIFLY WhoopStor V3 — 6-Port 1S LiPo Charger',
    category: 'FPV Drones', sub_category: 'batteries-chargers',
    price: calcPrice(29),
    image_url: ph('FPV Drones'),
    product_url: amz('B09YCVZZQ7'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'GNB 4S 1500mAh 100C — LiPo FPV Battery Pack',
    category: 'FPV Drones', sub_category: 'batteries-chargers',
    price: calcPrice(22),
    image_url: ph('FPV Drones'),
    product_url: amz('B082DFPC1J'),
    is_active: true, is_budget_king: true,
  },
  // More BNF
  {
    name: 'GEPRC Rocket Plus — 4" LR FPV Long Range Drone',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(229),
    image_url: ph('FPV Drones'),
    product_url: amz('B0B6BXHXXX'),
    is_active: true,
  },
  {
    name: 'iFlight Protek25 — Cinewhoop DJI O3 2.5"',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(259),
    image_url: ph('FPV Drones'),
    product_url: amz('B0C3HSLQKK'),
    is_active: true,
  },
  {
    name: 'BetaFPV Beta95X V3 — Whoop 2S 95mm FPV',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(89),
    image_url: ph('FPV Drones'),
    product_url: amz('B0847WHVDG'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'EMAX Hawk Apex — 5" FPV Freestyle BNF',
    category: 'FPV Drones', sub_category: 'bnf-drones',
    price: calcPrice(239),
    image_url: ph('FPV Drones'),
    product_url: amz('B0BKVTBZXN'),
    is_active: true,
  },
];
const SIM_RACING: SeedProduct[] = [
  // Wheel Bases
  {
    name: 'Moza R5 Bundle — Direct Drive Wheelbase + ES Wheel',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(329),
    image_url: 'https://m.media-amazon.com/images/I/71VLnGz9R4L._AC_SL1500_.jpg',
    product_url: amz('B0BN9H7WXJ'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Moza R9 — 9Nm Direct Drive Wheelbase',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(449),
    image_url: ph('Sim Racing'),
    product_url: amz('B0BN9GY2TF'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Moza R12 — 12Nm Direct Drive Wheelbase',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(649),
    image_url: ph('Sim Racing'),
    product_url: amz('B0C4KGHQ7Y'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Fanatec CSL DD — 8Nm Direct Drive PS5/PC',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(349),
    image_url: 'https://m.media-amazon.com/images/I/61jnkJv6nAL._AC_SL1500_.jpg',
    product_url: amz('B09F7VX2NZ'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Thrustmaster T300RS GT — Force Feedback Racing Wheel',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(299),
    image_url: 'https://m.media-amazon.com/images/I/71U0C7JYBPL._AC_SL1500_.jpg',
    product_url: amz('B00YY1CACK'),
    is_active: true,
  },
  {
    name: 'Logitech G29 Driving Force — Racing Wheel PS5/PC',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(249),
    image_url: 'https://m.media-amazon.com/images/I/81z+gW7CRBL._AC_SL1500_.jpg',
    product_url: amz('B00YUOYBE0'),
    is_active: true,
  },
  {
    name: 'Logitech G923 TRUEFORCE — Racing Wheel Xbox/PC',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(279),
    image_url: 'https://m.media-amazon.com/images/I/71VNHjIzO-L._AC_SL1500_.jpg',
    product_url: amz('B07YHKL69G'),
    is_active: true,
  },
  {
    name: 'Simucube 2 Pro — High Torque Direct Drive Wheelbase',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(1199),
    image_url: ph('Sim Racing'),
    product_url: amz('B08KHQ4RBJ'),
    is_active: true, is_top_tier: true,
  },
  // Pedals
  {
    name: 'Moza CRP Pedals — 3 Pedal Load Cell Set',
    category: 'Sim Racing', sub_category: 'pedals',
    price: calcPrice(199),
    image_url: 'https://m.media-amazon.com/images/I/71NuNvpBSJL._AC_SL1500_.jpg',
    product_url: amz('B0BNDH7P8T'),
    is_active: true,
  },
  {
    name: 'Fanatec CSL Pedals LC — Load Cell Brake 3-Pedal',
    category: 'Sim Racing', sub_category: 'pedals',
    price: calcPrice(179),
    image_url: 'https://m.media-amazon.com/images/I/61nOuiStO9L._AC_SL1500_.jpg',
    product_url: amz('B09F7SS6SR'),
    is_active: true,
  },
  {
    name: 'Thrustmaster T-LCM Pedals — Load Cell 3-Pedal Set',
    category: 'Sim Racing', sub_category: 'pedals',
    price: calcPrice(149),
    image_url: 'https://m.media-amazon.com/images/I/61g1xqQ0EFL._AC_SL1500_.jpg',
    product_url: amz('B08BWXPF5X'),
    is_active: true,
  },
  {
    name: 'Heusinkveld Sprint Pedals — Sim Racing Hydraulic Feel',
    category: 'Sim Racing', sub_category: 'pedals',
    price: calcPrice(379),
    image_url: ph('Sim Racing'),
    product_url: amz('B08XFBJ1K3'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Logitech G Driving Force Shifter — 6+1 Gear Shifter',
    category: 'Sim Racing', sub_category: 'shifters',
    price: calcPrice(59),
    image_url: 'https://m.media-amazon.com/images/I/81rdMRVQPCL._AC_SL1500_.jpg',
    product_url: amz('B00YY1CACY'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Fanatec ClubSport Shifter SQ V1.5 — Sequential/H-Pattern',
    category: 'Sim Racing', sub_category: 'shifters',
    price: calcPrice(179),
    image_url: ph('Sim Racing'),
    product_url: amz('B09NNYWMZG'),
    is_active: true,
  },
  // Handbrakes
  {
    name: 'Fanatec ClubSport Handbrake V1.5 — Sim Racing Hydraulic',
    category: 'Sim Racing', sub_category: 'handbrakes',
    price: calcPrice(149),
    image_url: ph('Sim Racing'),
    product_url: amz('B09G3GXVWR'),
    is_active: true,
  },
  {
    name: 'Moza HBP Handbrake — Premium Hydraulic Feel',
    category: 'Sim Racing', sub_category: 'handbrakes',
    price: calcPrice(99),
    image_url: ph('Sim Racing'),
    product_url: amz('B0C15YD3RW'),
    is_active: true,
  },
  // Cockpit Rigs
  {
    name: 'Next Level Racing GTtrack — Racing Cockpit F1/GT',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(449),
    image_url: 'https://m.media-amazon.com/images/I/71GUm1VRUZL._AC_SL1500_.jpg',
    product_url: amz('B07JZMN9YK'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Playseat Challenge X — Sim Racing Chair Folding',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(199),
    image_url: 'https://m.media-amazon.com/images/I/71gxOHJmNRL._AC_SL1500_.jpg',
    product_url: amz('B07Y6MTTKY'),
    is_active: true,
  },
  {
    name: 'GT Omega Prime Racing Chair — Sim Setup Seat',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(299),
    image_url: ph('Sim Racing'),
    product_url: amz('B08CYKCLBC'),
    is_active: true,
  },
  {
    name: 'Sparco SKY EVO — Gaming/Sim Racing Chair',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(349),
    image_url: ph('Sim Racing'),
    product_url: amz('B089B2FK5D'),
    is_active: true,
  },
  // Monitors
  {
    name: 'Samsung Odyssey G5 34" — Ultrawide Curved 165Hz WQHD',
    category: 'Sim Racing', sub_category: 'general',
    price: calcPrice(379),
    image_url: 'https://m.media-amazon.com/images/I/71bJ+7pfC5L._AC_SL1500_.jpg',
    product_url: amz('B08KJBMSGN'),
    is_active: true,
  },
  {
    name: 'LG UltraGear 27GP850-B — 27" 165Hz Nano IPS Gaming',
    category: 'Sim Racing', sub_category: 'general',
    price: calcPrice(299),
    image_url: ph('Sim Racing'),
    product_url: amz('B094NVMBHG'),
    is_active: true,
  },
  {
    name: 'AOC AG273QCX — 27" 144Hz Curved QHD Gaming',
    category: 'Sim Racing', sub_category: 'general',
    price: calcPrice(229),
    image_url: ph('Sim Racing'),
    product_url: amz('B083W4V2F3'),
    is_active: true, is_budget_king: true,
  },
  // Accessories
  {
    name: 'Wheel Stand Pro DELUXE V2 — Folding Racing Stand',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(89),
    image_url: 'https://m.media-amazon.com/images/I/71uSJmEJgBL._AC_SL1500_.jpg',
    product_url: amz('B00CLBX5SW'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Moza R3 Bundle — 5.5Nm DD Wheelbase + R3 Steering Wheel',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(229),
    image_url: ph('Sim Racing'),
    product_url: amz('B0CH5VPRLJ'),
    is_active: true,
  },
  {
    name: 'Fanatec Podium Steering Wheel F1 — Formula Esports',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(279),
    image_url: ph('Sim Racing'),
    product_url: amz('B07TQDLBB4'),
    is_active: true,
  },
  {
    name: 'Thrustmaster TH8A — Add-On Gear Shifter',
    category: 'Sim Racing', sub_category: 'shifters',
    price: calcPrice(69),
    image_url: 'https://m.media-amazon.com/images/I/81wBNqpxpwL._AC_SL1500_.jpg',
    product_url: amz('B00BTH3Q50'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Simucube 2 Sport — 17Nm Direct Drive Wheelbase',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(849),
    image_url: ph('Sim Racing'),
    product_url: amz('B09BSCDJN1'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Next Level Racing Flight & Driving Simulator Seat',
    category: 'Sim Racing', sub_category: 'cockpit-rigs',
    price: calcPrice(249),
    image_url: ph('Sim Racing'),
    product_url: amz('B07C22K33Q'),
    is_active: true,
  },
  {
    name: 'Logitech G PRO Racing Wheel — DD 11Nm Pro Level',
    category: 'Sim Racing', sub_category: 'steering-wheels',
    price: calcPrice(749),
    image_url: 'https://m.media-amazon.com/images/I/71I4Z6A1uEL._AC_SL1500_.jpg',
    product_url: amz('B0BQVMZ8X2'),
    is_active: true, is_top_tier: true,
  },
];
const CRYPTO_WALLETS: SeedProduct[] = [
  {
    name: 'Ledger Nano X — Hardware Wallet Bluetooth BTC/ETH/1800+ Coin',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(119),
    image_url: 'https://m.media-amazon.com/images/I/61PYSfn5WzL._AC_SL1500_.jpg',
    product_url: amz('B07M6R4NK3'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Ledger Nano S Plus — Hardware Wallet USB 5500+ Coin',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(59),
    image_url: 'https://m.media-amazon.com/images/I/41pLnuJpnPL._AC_SL1500_.jpg',
    product_url: amz('B09GDG17ZX'),
    is_active: true,
  },
  {
    name: 'Trezor Model T — Touchscreen Hardware Wallet 1000+ Coin',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(179),
    image_url: 'https://m.media-amazon.com/images/I/41iyTxRCt2L._AC_SL1500_.jpg',
    product_url: amz('B07HJDJ3MG'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Trezor Safe 3 — Hardware Wallet EAL6+ Secure Element',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(69),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B0CNKJ7MWC'),
    is_active: true,
  },
  {
    name: 'Ledger Stax — E-Ink Screen Premium Hardware Wallet',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(249),
    image_url: 'https://m.media-amazon.com/images/I/71VX8e-9cjL._AC_SL1500_.jpg',
    product_url: amz('B0CDMG8N7P'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Foundation Passport Batch 2 — Air-Gapped Bitcoin Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(199),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09JFBXHXQ'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'BitBox02 Multi Edition — Open Source Hardware Wallet',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(99),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07SY9FKWM'),
    is_active: true,
  },
  {
    name: 'Coldcard Mk4 — Bitcoin Air-Gapped Ultra-Secure Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(149),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09K6W4B4K'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'KeepKey — Hardware Wallet BTC/ETH/LTC Crypto',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(39),
    image_url: 'https://m.media-amazon.com/images/I/71sE59C7XJL._AC_SL1500_.jpg',
    product_url: amz('B0143M2A5S'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Cryptosteel Capsule Solo — Indestructible Seed Phrase Backup',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(69),
    image_url: 'https://m.media-amazon.com/images/I/71J+vu6k6ZL._AC_SL1500_.jpg',
    product_url: amz('B07KFR7ZNX'),
    is_active: true,
  },
  {
    name: 'Billfodl — Stainless Steel Seed Backup Plate',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(79),
    image_url: 'https://m.media-amazon.com/images/I/61w3VNLNm7L._AC_SL1500_.jpg',
    product_url: amz('B07TXFHD4F'),
    is_active: true,
  },
  {
    name: 'Cryptotag Zeus — Titanium Seed Phrase Backup',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(99),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07V8GVXJK'),
    is_active: true,
  },
  {
    name: 'Blockplate — Stainless Steel Seed Storage Plate',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(35),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07YCHRD9W'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Ledger Nano X — Crypto Starter Pack BTC Starter Kit',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(109),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07M6R4NK4'),
    is_active: true,
  },
  {
    name: 'D\'CENT Biometric Wallet — Fingerprint Cold Storage',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(109),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07W9NCZSY'),
    is_active: true,
  },
  {
    name: 'Ellipal Titan 2.0 — Air-Gapped QR Code Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(139),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09YMQ9V3L'),
    is_active: true,
  },
  {
    name: 'SafePal S1 Pro — Offline Crypto Wallet + QR Code',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(49),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09TXWGR7X'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Ledger Nano S Plus — Crypto Hardware Wallet BTC/ETH',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(55),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09GDG17ZY'),
    is_active: true,
  },
  {
    name: 'Trezor One — Entry Level Crypto Hardware Wallet',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(49),
    image_url: 'https://m.media-amazon.com/images/I/41ELj0UUvQL._AC_SL1000_.jpg',
    product_url: amz('B01J66NF46'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Ledger Flex — Touchscreen Hardware Wallet Gen3',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(199),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B0CNKJ9RG2'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Keystone 3 Pro — Triple Chip Air-Gapped Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(149),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B0BXP23FGK'),
    is_active: true,
  },
  {
    name: 'NGRAVE ZERO — EAL7 Air-Gapped Cold Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(299),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B08XTJXJG4'),
    is_active: true, is_top_tier: true,
  },
  {
    name: 'Cryptosteel Cassette — DIY Metal Seed Backup',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(89),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07DPVFBQG'),
    is_active: true,
  },
  {
    name: 'Metal Bitcoin Seed Storage — Stainless 2-Plate Backup',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(28),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07B5JBSMV'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Steelwallet — Stainless BIP39 Seed Phrase Backup',
    category: 'Crypto Wallets', sub_category: 'backup-seed',
    price: calcPrice(59),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07Z4KXYHK'),
    is_active: true,
  },
  {
    name: 'SecuX W20 — Wireless Crypto Hardware Wallet NFC',
    category: 'Crypto Wallets', sub_category: 'premium',
    price: calcPrice(119),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07LDSYZ4P'),
    is_active: true,
  },
  {
    name: 'CoolWallet Pro — Bluetooth Credit Card Crypto Wallet',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(79),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B08RHK2LTW'),
    is_active: true,
  },
  {
    name: 'Ballet REAL Bitcoin Wallet — Physical Metal Card',
    category: 'Crypto Wallets', sub_category: 'entry-level',
    price: calcPrice(29),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B085RGLF74'),
    is_active: true, is_budget_king: true,
  },
  {
    name: 'Passport Founder Edition — Bitcoin Open Source Wallet',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(249),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B09JGH7H5Q'),
    is_active: true,
  },
  {
    name: 'BitBox02 Bitcoin Only Edition — Open Source BTC',
    category: 'Crypto Wallets', sub_category: 'air-gapped',
    price: calcPrice(89),
    image_url: ph('Crypto Wallets'),
    product_url: amz('B07SY9FKWN'),
    is_active: true,
  },
];
const CYBER_SECURITY: SeedProduct[] = [
  // Pentest / Research Hardware
  {
    // #1 — not on Amazon IT, official link
    name: 'Flipper Zero — Multi-Tool Device per Pentest e RF Research',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(120),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.flipperzero.one/',
    is_active: true, is_top_tier: true,
    description: 'Multi-tool portatile per sub-GHz, NFC, RFID, IR, GPIO. Legale per ricerca e audit su propri dispositivi.',
  },
  {
    // #2 — Hak5, link ufficiale
    name: 'USB Rubber Ducky (Hak5) — Keystroke Injection Tool',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(45),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.hak5.org/products/usb-rubber-ducky',
    is_active: true,
    description: 'HID injection device per pentest e automazione. Legale per audit su propri sistemi.',
  },
  {
    // #3 — Hak5
    name: 'Bash Bunny (Hak5) — Multi-Vector USB Attack Platform',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(90),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.hak5.org/products/bash-bunny',
    is_active: true,
    description: 'Piattaforma USB dual-mode per pentest: emula tastiera, storage, Ethernet. Uso autorizzato su propri sistemi.',
  },
  {
    // #4 — Hak5
    name: 'WiFi Pineapple Mark VII (Hak5) — Wireless Auditing Platform',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(100),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.hak5.org/products/wifi-pineapple',
    is_active: true, is_top_tier: true,
    description: 'Piattaforma professionale per audit reti WiFi. Uso legale esclusivamente su reti proprie/autorizzate.',
  },
  {
    // #5 — Hak5
    name: 'LAN Turtle (Hak5) — Covert Sysadmin Remote Access',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(50),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.hak5.org/products/lan-turtle',
    is_active: true,
    description: 'Adattatore USB-Ethernet per sysadmin remoto e network recon. Legale per audit infrastrutture proprie.',
  },
  {
    // #6 — Hak5
    name: 'OMG Cable (Hak5) — Advanced Implant Cable for Pentest',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(120),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.hak5.org/products/omg-cable',
    is_active: true,
    description: 'Cavo con impianto wireless per HID injection e pentest. Solo uso su dispositivi propri/autorizzati.',
  },
  {
    // #7 — HackRF One, available on Amazon IT
    name: 'HackRF One (Great Scott Gadgets) — SDR Transceiver 1MHz-6GHz',
    category: 'Cyber Security', sub_category: 'sdr-rf',
    price: calcPrice(290),
    image_url: 'https://m.media-amazon.com/images/I/51pO3ZfM6xL._AC_SL1000_.jpg',
    product_url: amz('B01K1CCHR0'),
    is_active: true, is_top_tier: true,
    description: 'SDR transceiver half-duplex 1MHz-6GHz. Ricerca RF, analisi segnali, radio security research.',
  },
  {
    // #8 — Proxmark3 Easy, available on Amazon IT
    name: 'Proxmark3 Easy — RFID/NFC Research & Cloning Tool',
    category: 'Cyber Security', sub_category: 'rfid-nfc',
    price: calcPrice(55),
    image_url: 'https://m.media-amazon.com/images/I/51yVD01RD9L._AC_SL1000_.jpg',
    product_url: amz('B07KZTN1DX'),
    is_active: true,
    description: 'Tool per ricerca RFID/NFC, lettura e analisi di tag. Legale per ricerca su proprie carte/badge.',
  },
  {
    // #9 — ACR122U, available on Amazon IT
    name: 'NFC ACR122U (ACS) — USB NFC Reader/Writer ISO 18092',
    category: 'Cyber Security', sub_category: 'rfid-nfc',
    price: calcPrice(28),
    image_url: 'https://m.media-amazon.com/images/I/51r5sDCwTCL._AC_SL1000_.jpg',
    product_url: amz('B07KXCNBHY'),
    is_active: true, is_budget_king: true,
    description: 'Reader NFC USB compatibile con ISO 14443 A/B e ISO 18092. Ideale per sviluppo e ricerca NFC.',
  },
  // Hardware Security Keys
  {
    // #10
    name: 'YubiKey 5 NFC — Multi-Protocol Security Key USB-A + NFC',
    category: 'Cyber Security', sub_category: 'hardware-keys',
    price: calcPrice(45),
    image_url: 'https://m.media-amazon.com/images/I/61EI0CJXJQL._AC_SL1500_.jpg',
    product_url: amz('B08DHL1YDL'),
    is_active: true, is_top_tier: true,
  },
  {
    // #11
    name: 'YubiKey 5C NFC — Security Key USB-C + NFC FIDO2',
    category: 'Cyber Security', sub_category: 'hardware-keys',
    price: calcPrice(55),
    image_url: 'https://m.media-amazon.com/images/I/41bFQ-lSdEL._AC_SL1500_.jpg',
    product_url: amz('B09WPGGCS1'),
    is_active: true, is_top_tier: true,
  },
  {
    // #12
    name: 'Nitrokey 3A NFC — Open Source USB Security Token',
    category: 'Cyber Security', sub_category: 'hardware-keys',
    price: calcPrice(29),
    image_url: ph('Cyber Security'),
    product_url: amz('B0B68J7DXJ'),
    is_active: true, is_budget_king: true,
  },
  {
    // #13
    name: 'OnlyKey (CryptoTrust) — Password Manager Hardware + 2FA',
    category: 'Cyber Security', sub_category: 'hardware-keys',
    price: calcPrice(39),
    image_url: ph('Cyber Security'),
    product_url: amz('B06Y1CSJ9H'),
    is_active: true,
  },
  // VPN Routers (legal replacements for jammers/interceptors)
  {
    // #14 — rimpiazzo WiFi Jammer
    name: 'GL.iNet Beryl AX (MT3000) — Travel VPN Router WiFi 6',
    category: 'Cyber Security', sub_category: 'vpn-routers',
    price: calcPrice(79),
    image_url: 'https://m.media-amazon.com/images/I/71FVTw7GHAL._AC_SL1500_.jpg',
    product_url: amz('B0B9SMYVQ4'),
    is_active: true, is_top_tier: true,
    description: 'Router travel WiFi 6 con VPN integrata (WireGuard/OpenVPN). Rimpiazzo legale per protezione rete rispetto a jammer.',
  },
  {
    // #15 — rimpiazzo GSM Interceptor
    name: 'GL.iNet Slate AX (AXT1800) — VPN Router WiFi 6 OpenWRT',
    category: 'Cyber Security', sub_category: 'vpn-routers',
    price: calcPrice(89),
    image_url: 'https://m.media-amazon.com/images/I/71XkMqQO9fL._AC_SL1500_.jpg',
    product_url: amz('B09F95LHZJ'),
    is_active: true, is_top_tier: true,
    description: 'Router OpenWRT WiFi 6 con VPN integrata. Protezione proattiva delle comunicazioni vs intercettazione passiva.',
  },
  {
    // #16 — rimpiazzo Evil Twin Kit
    name: 'Alfa Network AWUS036ACH — USB WiFi Adapter Dual Band Monitor Mode',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(35),
    image_url: 'https://m.media-amazon.com/images/I/71u7zmSS5cL._AC_SL1500_.jpg',
    product_url: amz('B00VEEBOPG'),
    is_active: true,
    description: 'Adattatore WiFi USB dual-band con monitor mode e packet injection. Per ricerca wireless e audit reti proprie.',
  },
  {
    // #17 — rimpiazzo GSM Interceptor / SDR legale
    name: 'RTL-SDR Blog V4 — SDR Receiver DVB-T USB Dongle',
    category: 'Cyber Security', sub_category: 'sdr-rf',
    price: calcPrice(32),
    image_url: 'https://m.media-amazon.com/images/I/71EwqKM+WtL._AC_SL1500_.jpg',
    product_url: amz('B0CD745394'),
    is_active: true, is_budget_king: true,
    description: 'SDR receiver USB economico per analisi spettro radio, ADS-B, ACARS. Solo ricezione, uso legale.',
  },
  // USB Protection (legal replacement for USB Killer)
  {
    // #18 — rimpiazzo USB Killer
    name: 'PortaPow USB Data Blocker — Charge-Only Safe Charging',
    category: 'Cyber Security', sub_category: 'privacy-tools',
    price: calcPrice(8),
    image_url: 'https://m.media-amazon.com/images/I/71V6g9jZrGL._AC_SL1500_.jpg',
    product_url: amz('B00T0DW3F8'),
    is_active: true, is_budget_king: true,
    description: 'Blocca i pin dati USB consentendo solo la ricarica. Protezione anti-juice jacking. Sostituto legale USB Killer.',
  },
  // Faraday & RFID
  {
    // #19
    name: 'Faraday Bag OffGrid — Laptop/Tablet Signal Blocker EMF',
    category: 'Cyber Security', sub_category: 'faraday-rfid',
    price: calcPrice(29),
    image_url: 'https://m.media-amazon.com/images/I/71G3FVNnXwL._AC_SL1500_.jpg',
    product_url: amz('B07Y49T8YC'),
    is_active: true,
    description: 'Faraday bag per laptop con blocco GSM/4G/WiFi/NFC. Protezione da tracking e segnali indesiderati.',
  },
  {
    // #20
    name: 'RFID Blocking Wallet Travelambo — Slim Aluminum Card Holder',
    category: 'Cyber Security', sub_category: 'faraday-rfid',
    price: calcPrice(18),
    image_url: 'https://m.media-amazon.com/images/I/71ERAnVbw5L._AC_SL1500_.jpg',
    product_url: amz('B01G3T4AXI'),
    is_active: true, is_budget_king: true,
  },
  // Privacy Tools
  {
    // #21
    name: '3M Privacy Screen Filter 14" — Anti-Spy Laptop Screen',
    category: 'Cyber Security', sub_category: 'privacy-tools',
    price: calcPrice(29),
    image_url: 'https://m.media-amazon.com/images/I/71BEJXRHf9L._AC_SL1500_.jpg',
    product_url: amz('B073WQKMKL'),
    is_active: true,
    description: 'Filtro privacy 3M per laptop 14". Blocco visuale laterale a 60°. Indispensabile in ambienti pubblici.',
  },
  // Encrypted Storage
  {
    // #22
    name: 'Kingston IronKey D300 — Encrypted USB Drive 16GB FIPS 140-2',
    category: 'Cyber Security', sub_category: 'encrypted-storage',
    price: calcPrice(75),
    image_url: ph('Cyber Security'),
    product_url: amz('B07YGWP2TY'),
    is_active: true,
    description: 'USB drive crittografato AES 256-bit XTS, certificato FIPS 140-2 Level 3. Per dati sensibili in mobilità.',
  },
  {
    // #23
    name: 'iStorage datAshur Pro — PIN Protected USB Drive 16GB',
    category: 'Cyber Security', sub_category: 'encrypted-storage',
    price: calcPrice(95),
    image_url: 'https://m.media-amazon.com/images/I/51RCNcl2vRL._AC_SL1500_.jpg',
    product_url: amz('B019F98RL2'),
    is_active: true, is_top_tier: true,
    description: 'USB drive con PIN fisico e crittografia AES 256-bit. Auto-cancella dopo 10 tentativi errati.',
  },
  {
    // #24 — legale per audit proprio PC
    name: 'KeyGrabber USB — Hardware Keylogger Audit proprio PC',
    category: 'Cyber Security', sub_category: 'pentest-hardware',
    price: calcPrice(40),
    image_url: ph('Cyber Security'),
    product_url: amz('B01N1UXGV4'),
    is_active: true,
    description: 'Hardware keylogger USB per audit e monitoraggio proprio PC. Legale solo su sistemi di propria proprietà.',
  },
  {
    // #25 — Proxmark3 RDV4
    name: 'Proxmark3 RDV4 (Elechouse) — Advanced RFID Research Kit',
    category: 'Cyber Security', sub_category: 'rfid-nfc',
    price: calcPrice(180),
    image_url: ph('Cyber Security'),
    product_url: amz('B08NY3NLL9'),
    is_active: true, is_top_tier: true,
    description: 'Kit professionale per ricerca RFID/NFC con batteria integrata. Versione avanzata del Proxmark3.',
  },
  // Surveillance / Legal recording
  {
    // #26
    name: 'Sony ICD-PX470 — Digital Voice Recorder Stereo',
    category: 'Cyber Security', sub_category: 'surveillance-legal',
    price: calcPrice(55),
    image_url: 'https://m.media-amazon.com/images/I/71oNHzCeWRL._AC_SL1500_.jpg',
    product_url: amz('B01AS8EJZQ'),
    is_active: true,
    description: 'Registratore vocale digitale stereo Sony. Legale per registrare proprie conversazioni e note.',
  },
  {
    // #27 — GPS per veicoli propri
    name: 'Optimus 2.0 — GPS Tracker Veicoli Propri (4G)',
    category: 'Cyber Security', sub_category: 'surveillance-legal',
    price: calcPrice(35),
    image_url: ph('Cyber Security'),
    product_url: amz('B07JHQM51G'),
    is_active: true,
    description: 'GPS tracker 4G per localizzazione veicoli propri. Abbonamento mensile richiesto. Legale su veicoli di proprietà.',
  },
  {
    // #28 — USB Condom / PortaPow Fast Charge
    name: 'PortaPow Fast Charge USB Data Blocker — USB-C Version',
    category: 'Cyber Security', sub_category: 'privacy-tools',
    price: calcPrice(10),
    image_url: ph('Cyber Security'),
    product_url: amz('B094FYL9QT'),
    is_active: true, is_budget_king: true,
    description: 'Data blocker USB-C con supporto fast charge. Protegge da juice jacking su porte USB pubbliche.',
  },
  {
    // #29 — Librem Key
    name: 'Librem Key (Purism) — OpenPGP USB Security Token',
    category: 'Cyber Security', sub_category: 'hardware-keys',
    price: calcPrice(55),
    image_url: ph('Cyber Security'),
    product_url: 'https://shop.puri.sm/shop/librem-key/',
    is_active: true,
    description: 'Token di sicurezza USB OpenPGP di Purism. Open source, compatibile con GPG e SSH. Non disponibile su Amazon IT.',
  },
  {
    // #30 — Bluetooth Tracker Detector
    name: 'Mystical Tech Bluetooth Tracker Detector — Anti-AirTag Scanner',
    category: 'Cyber Security', sub_category: 'surveillance-legal',
    price: calcPrice(28),
    image_url: ph('Cyber Security'),
    product_url: amz('B0BHKM88CL'),
    is_active: true,
    description: 'Rilevatore di tracker Bluetooth nascosti (AirTag, Tile, ecc.). Scansione attiva per protezione dalla sorveglianza.',
  },
];
