/**
 * FIX-IMAGES — Aggiorna image_url dei prodotti nel DB che hanno URL rotte
 * (URL costruite con ASIN anziché con il vero ID immagine Amazon)
 *
 * Run:  npx tsx scripts/fix-images.ts
 *
 * Per ogni prodotto con image_url che contiene un ASIN (es. B08H5K7N3L):
 *  1. Estrae ASIN dall'affiliate_url
 *  2. Fetcha la pagina Amazon /dp/ASIN/
 *  3. Estrae og:image / landingImageUrl / data-old-hires
 *  4. Aggiorna image_url in Supabase
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';
import { resolve } from 'path';

function loadEnv() {
  try {
    const raw = readFileSync(resolve(process.cwd(), '.env.local'), 'utf-8');
    for (const line of raw.split('\n')) {
      const eqIdx = line.indexOf('=');
      if (eqIdx === -1) continue;
      const key = line.slice(0, eqIdx).trim();
      const val = line.slice(eqIdx + 1).trim();
      if (key) process.env[key] = val;
    }
  } catch { /* ignore */ }
}

loadEnv();

const C = {
  reset:   '\x1b[0m',
  bright:  '\x1b[1m',
  cyan:    '\x1b[36m',
  green:   '\x1b[32m',
  yellow:  '\x1b[33m',
  red:     '\x1b[31m',
  gray:    '\x1b[90m',
};

function log(color: string, tag: string, msg: string) {
  const ts = new Date().toLocaleTimeString('it-IT');
  console.log(`${C.gray}${ts}${C.reset} ${color}${C.bright}[${tag}]${C.reset} ${msg}`);
}

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!.trim(),
  process.env.SUPABASE_SERVICE_ROLE_KEY!.trim(),
);

const USER_AGENTS = [
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36',
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
];
let uaIdx = 0;
const nextUA = () => USER_AGENTS[uaIdx++ % USER_AGENTS.length];

function delay(min = 3000, max = 5000): Promise<void> {
  const ms = Math.floor(Math.random() * (max - min + 1)) + min;
  log(C.yellow, 'WAIT', `Attendo ${(ms / 1000).toFixed(1)}s...`);
  return new Promise((r) => setTimeout(r, ms));
}

/** Restituisce true se image_url è rotta: ASIN-based o ID fittizio con caratteri ripetuti */
function isAsinBasedUrl(url: string): boolean {
  if (!/\/images\/I\//.test(url)) return false;
  // Bare ASIN (10 chars) no suffix
  if (/\/images\/I\/[A-Z0-9]{10}\.jpg$/i.test(url)) return true;
  // Fake repetitive-char ID generated by agents (e.g. 41Q7Q7Q7Q7L, 51E5E5E5E5L)
  const imgId = url.match(/\/images\/I\/([A-Za-z0-9+%]{8,})\._/)?.[1];
  if (imgId && /(.{2,})\1{2,}/.test(imgId)) return true;
  return false;
}

function extractAsinFromUrl(url: string): string | null {
  const m = url.match(/\/dp\/([A-Z0-9]{10})(?:[/?#]|$)/i);
  return m ? m[1].toUpperCase() : null;
}

async function fetchRealImageUrl(asin: string): Promise<string | null> {
  try {
    const res = await fetch(`https://www.amazon.it/dp/${asin}/`, {
      headers: {
        'User-Agent':      nextUA(),
        'Accept':          'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'it-IT,it;q=0.9',
        'Accept-Encoding': 'gzip, deflate, br',
        'Cache-Control':   'no-cache',
      },
      signal: AbortSignal.timeout(15_000),
    });

    if (!res.ok) {
      log(C.yellow, 'HTTP', `Amazon risponde ${res.status} per ${asin}`);
      return null;
    }

    const html = await res.text();

    if (html.toLowerCase().includes('captcha') || html.includes('Type the characters')) {
      log(C.yellow, 'CAPTCHA', `Amazon ha mostrato CAPTCHA per ${asin}`);
      return null;
    }

    // 1. og:image
    const og = html.match(/<meta[^>]+property=["']og:image["'][^>]+content=["'](https:\/\/[^"']+)["']/i)
            ?? html.match(/<meta[^>]+content=["'](https:\/\/m\.media-amazon\.com\/images\/I\/[^"']+)["'][^>]+property=["']og:image["']/i);
    if (og?.[1]) return og[1];

    // 2. landingImageUrl in JS
    const landing = html.match(/"landingImageUrl"\s*:\s*"(https:\/\/[^"]+)"/);
    if (landing?.[1]) return landing[1];

    // 3. data-old-hires
    const hiRes = html.match(/data-old-hires="(https:\/\/[^"]+)"/);
    if (hiRes?.[1]) return hiRes[1];

    // 4. Qualsiasi immagine media-amazon con ID non-ASIN (almeno 12 char)
    const anyImg = html.match(/https:\/\/m\.media-amazon\.com\/images\/I\/([A-Za-z0-9]{12,})\._/);
    if (anyImg) return `https://m.media-amazon.com/images/I/${anyImg[1]}._AC_SL500_.jpg`;

    log(C.yellow, 'IMG', `Nessuna immagine trovata per ${asin}`);
    return null;

  } catch (err: unknown) {
    log(C.red, 'ERROR', `Fetch fallita per ${asin}: ${err instanceof Error ? err.message : String(err)}`);
    return null;
  }
}

async function main() {
  console.log(`\n${C.bright}${C.cyan}${'━'.repeat(54)}${C.reset}`);
  console.log(`${C.bright}${C.cyan}   FIX-IMAGES — Aggiorna immagini rotte nel DB${C.reset}`);
  console.log(`${C.bright}${C.cyan}${'━'.repeat(54)}${C.reset}\n`);

  // Carica tutti i prodotti
  const { data, error } = await supabase
    .from('products')
    .select('id, name, image_url, affiliate_url, product_url');

  if (error) throw new Error(`Supabase: ${error.message}`);
  if (!data || data.length === 0) {
    log(C.yellow, 'DB', 'Nessun prodotto nel DB');
    return;
  }

  // Filtra solo quelli con URL rotta
  const broken = (data as Array<{ id: string; name: string; image_url: string; affiliate_url: string; product_url: string }>)
    .filter((p) => !p.image_url || isAsinBasedUrl(p.image_url) || p.image_url.includes('placeholder'));

  log(C.cyan, 'SCAN', `Trovati ${broken.length} prodotti con immagine da aggiornare (su ${data.length} totali)\n`);

  if (broken.length === 0) {
    log(C.green, 'OK', 'Tutte le immagini sono già corrette!');
    return;
  }

  let fixed   = 0;
  let skipped = 0;
  let failed  = 0;

  for (let i = 0; i < broken.length; i++) {
    const p = broken[i];
    console.log(`\n${C.bright}${C.yellow}── [${i + 1}/${broken.length}] ${p.name} ──${C.reset}`);

    const asin = extractAsinFromUrl(p.product_url ?? p.affiliate_url ?? '');
    if (!asin) {
      log(C.red, 'SKIP', `Nessun ASIN in product_url o affiliate_url — salto`);
      skipped++;
      continue;
    }

    log(C.cyan, 'ASIN', asin);
    const newUrl = await fetchRealImageUrl(asin);

    if (!newUrl) {
      log(C.yellow, 'SKIP', `Impossibile ottenere immagine reale — lascio invariato`);
      skipped++;
    } else if (newUrl === p.image_url) {
      log(C.gray, 'SAME', `URL invariata — nessun update necessario`);
      skipped++;
    } else {
      const { error: upErr } = await supabase
        .from('products')
        .update({ image_url: newUrl })
        .eq('id', p.id);

      if (upErr) {
        log(C.red, 'ERR', `Update fallito: ${upErr.message}`);
        failed++;
      } else {
        log(C.green, 'FIXED', `✓ ${newUrl.slice(0, 80)}...`);
        fixed++;
      }
    }

    if (i < broken.length - 1) await delay(1500, 3000);
  }

  console.log(`\n${C.bright}${C.cyan}${'─'.repeat(54)}${C.reset}`);
  console.log(`${C.bright}${C.green}  ✓ Aggiornati: ${fixed}${C.reset}`);
  console.log(`${C.bright}${C.yellow}  ↺ Saltati:    ${skipped}${C.reset}`);
  if (failed > 0)
    console.log(`${C.bright}${C.red}  ✗ Errori:     ${failed}${C.reset}`);
  console.log(`${C.bright}${C.cyan}${'─'.repeat(54)}${C.reset}\n`);
}

main().catch((err: unknown) => {
  console.error(C.red + '[FATAL] ' + (err instanceof Error ? err.message : String(err)) + C.reset);
  process.exit(1);
});
