/**
 * Seed Catalogo - 50 Prodotti ad Alta Rotazione
 *
 * Esegui con:
 *   npm run seed
 *
 * Requisiti:
 *   - NEXT_PUBLIC_SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY in .env.local
 */

import { createClient } from '@supabase/supabase-js'
import type { ProductInsert } from '../types/supabase'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseUrl || !serviceKey) {
  console.error('Mancano NEXT_PUBLIC_SUPABASE_URL o SUPABASE_SERVICE_ROLE_KEY nel .env.local')
  process.exit(1)
}

const db = createClient(supabaseUrl, serviceKey)

// Prezzo con margine 20% arrotondato a .99
function p(supplierPrice: number): number {
  return Math.ceil(supplierPrice * 1.2) - 0.01
}

const PLACEHOLDER = 'https://placehold.co/600x400/1a1a1a/ffffff?text=Immagine+Prodotto'

const products: ProductInsert[] = [
  // ══════════════════════════════════════
  //  PERIFERICHE GAMING (15 prodotti)
  // ══════════════════════════════════════
  {
    title: 'Logitech G Pro X Superlight',
    slug: 'logitech-g-pro-x-superlight',
    category: 'Mouse',
    price_current: p(90),
    price_original: null,
    currency: 'EUR',
    description: 'Il mouse wireless da 61g preferito dai pro player esport. Sensore HERO 25K con precisione assoluta, batteria da 70 ore — nessun compromesso tra leggerezza e prestazioni.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { weight_g: 61, dpi: 25600, connectivity: 'Wireless LIGHTSPEED', battery_life: '70 ore' },
    meta_title: 'Logitech G Pro X Superlight — Mouse Pro Gaming',
    meta_description: 'Mouse wireless 61g con sensore HERO 25K. Il preferito dei pro player esport.',
  },
  {
    title: 'Razer DeathAdder V3',
    slug: 'razer-deathadder-v3',
    category: 'Mouse',
    price_current: p(65),
    price_original: null,
    currency: 'EUR',
    description: 'Forma ergonomica iconica reingegnerizzata, ora al 30% più leggera. Sensore Focus Pro 30K per tracking ultra-preciso su qualsiasi superficie.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { weight_g: 59, dpi: 30000, connectivity: 'Cablato USB-C', polling_rate: '8000Hz' },
    meta_title: 'Razer DeathAdder V3 — Mouse Ergonomico Gaming',
    meta_description: 'Forma ergonomica classica, sensore 30K DPI, solo 59g. Preciso e confortevole.',
  },
  {
    title: 'SteelSeries Apex Pro',
    slug: 'steelseries-apex-pro',
    category: 'Tastiera',
    price_current: p(130),
    price_original: null,
    currency: 'EUR',
    description: 'La prima tastiera al mondo con switch magnetici OmniPoint 2.0 a sensibilità regolabile. Scegli il punto di attuazione da 0.1 a 4mm per ogni singolo tasto.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: 'TKL', switch_type: 'OmniPoint 2.0 Magnetic', actuation_range: '0.1–4mm', backlight: 'RGB per-key' },
    meta_title: 'SteelSeries Apex Pro — Tastiera Gaming Switch Regolabili',
    meta_description: 'Switch magnetici con attuazione personalizzabile da 0.1mm. La tastiera più avanzata per gaming competitivo.',
  },
  {
    title: 'Keychron Q1',
    slug: 'keychron-q1',
    category: 'Tastiera',
    price_current: p(85),
    price_original: null,
    currency: 'EUR',
    description: 'Scocca in alluminio CNC, montaggio gasket per un suono pieno e taktile. Hot-swappable e programmabile QMK/VIA. Il custom meccanico accessibile per tutti.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: '75%', material: 'Alluminio CNC', hot_swappable: true, connectivity: 'USB-C' },
    meta_title: 'Keychron Q1 — Tastiera Meccanica Custom Alluminio',
    meta_description: 'Tastiera meccanica 75% in alluminio, gasket mount, QMK/VIA. Qualità custom a prezzo accessibile.',
  },
  {
    title: 'HyperX Alloy Origins',
    slug: 'hyperx-alloy-origins',
    category: 'Tastiera',
    price_current: p(65),
    price_original: null,
    currency: 'EUR',
    description: 'Struttura full-size in acciaio aeronautico ultra-resistente con switch HyperX Red lineari. Illuminazione RGB a 3 zone per sessioni di gioco prolungate.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: 'Full-size', switch_type: 'HyperX Red Linear', material: 'Acciaio aeronautico', backlight: 'RGB 3 zone' },
    meta_title: 'HyperX Alloy Origins — Tastiera Gaming in Acciaio',
    meta_description: 'Tastiera meccanica full-size con struttura in acciaio e switch HyperX Red. Solida, silenziosa e luminosa.',
  },
  {
    title: 'ASUS TUF Gaming K3',
    slug: 'asus-tuf-gaming-k3',
    category: 'Tastiera',
    price_current: p(50),
    price_original: null,
    currency: 'EUR',
    description: 'Tastiera TKL compatta con switch lineari silenziosi e resistenza IPX4 agli schizzi. Solida per chi cerca prestazioni gaming senza spendere una fortuna.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: 'TKL', water_resistance: 'IPX4', switch_type: 'Linear Red', backlight: 'RGB' },
    meta_title: 'ASUS TUF Gaming K3 — Tastiera TKL Resistente agli Schizzi',
    meta_description: 'Tastiera TKL gaming con resistenza IPX4 e switch lineari. Compatta e duratura.',
  },
  {
    title: 'Logitech G502 X',
    slug: 'logitech-g502-x',
    category: 'Mouse',
    price_current: p(55),
    price_original: null,
    currency: 'EUR',
    description: 'Il best-seller di Logitech reingegnerizzato con switch ottico LIGHTFORCE. Sensore HERO 25K, design ergonomico con 13 tasti programmabili per il massimo controllo.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { weight_g: 89, dpi: 25600, switch_type: 'LIGHTFORCE Optical', buttons: 13 },
    meta_title: 'Logitech G502 X — Mouse Gaming Ergonomico',
    meta_description: 'G502 con switch ottici LIGHTFORCE e sensore HERO 25K. 13 tasti programmabili per il massimo controllo.',
  },
  {
    title: 'Razer Huntsman Mini',
    slug: 'razer-huntsman-mini',
    category: 'Tastiera',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'Tastiera 60% con switch ottici al laser più veloci al mondo. Compatta, portatile e con risposta istantanea — la scelta dei gamer che non vogliono rinunciare alla velocità.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: '60%', switch_type: 'Razer Linear Optical', actuation_point: '1mm', backlight: 'RGB Chroma' },
    meta_title: 'Razer Huntsman Mini — Tastiera 60% Switch Ottici',
    meta_description: 'Tastiera 60% compatta con switch ottici laser. Risposta istantanea per gaming competitivo.',
  },
  {
    title: 'Corsair K70 RGB',
    slug: 'corsair-k70-rgb',
    category: 'Tastiera',
    price_current: p(95),
    price_original: null,
    currency: 'EUR',
    description: 'Struttura in alluminio anodizzato con macro dedicati e poggiapolsi morbido rimovibile. Switch Cherry MX e RGB per-key: la tastiera premium completa.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { layout: 'Full-size', switch_type: 'Cherry MX Red', material: 'Alluminio anodizzato', wrist_rest: true },
    meta_title: 'Corsair K70 RGB — Tastiera Meccanica Premium',
    meta_description: 'Struttura alluminio, Cherry MX, RGB per-key e poggiapolsi. La tastiera premium definitiva.',
  },
  {
    title: 'Glorious Model O',
    slug: 'glorious-model-o',
    category: 'Mouse',
    price_current: p(40),
    price_original: null,
    currency: 'EUR',
    description: 'Design honeycomb ultraleggero da soli 67g con cavo flessibile. Sensore Pixart 3360, 6 tasti programmabili. Il miglior rapporto qualità/prezzo nel gaming.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { weight_g: 67, dpi: 12000, design: 'Honeycomb', cable: 'Ascended Cord flessibile' },
    meta_title: 'Glorious Model O — Mouse Ultraleggero Honeycomb',
    meta_description: 'Mouse honeycomb da 67g con sensore 3360. Massima leggerezza al minimo prezzo.',
  },
  {
    title: 'SteelSeries Arctis Nova 7',
    slug: 'steelseries-arctis-nova-7',
    category: 'Cuffie',
    price_current: p(95),
    price_original: null,
    currency: 'EUR',
    description: 'Cuffie wireless con connessione simultanea 2.4GHz + Bluetooth. Audio ClearCast Gen 2 con AI noise cancelling. 38 ore di autonomia per gaming e smartworking senza confini.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: '2.4GHz + Bluetooth 5.0', battery_life: '38 ore', microphone: 'ClearCast Gen2 AI', frequency_response: '20Hz–20kHz' },
    meta_title: 'SteelSeries Arctis Nova 7 — Cuffie Wireless Gaming',
    meta_description: 'Wireless 2.4GHz + BT, 38h batteria, AI noise cancelling. Le cuffie wireless più complete.',
  },
  {
    title: 'HyperX Cloud Alpha',
    slug: 'hyperx-cloud-alpha',
    category: 'Cuffie',
    price_current: p(60),
    price_original: null,
    currency: 'EUR',
    description: 'Camera dual acustica brevettata per bassi profondi senza distorsione. Microfono staccabile con cancellazione rumore. Build in alluminio per durare anni.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: '3.5mm + USB audio box', driver_size: '50mm dual chamber', microphone: 'Staccabile noise-cancel', weight_g: 298 },
    meta_title: 'HyperX Cloud Alpha — Cuffie Gaming Dual Chamber',
    meta_description: 'Cuffie gaming con driver dual chamber, microfono staccabile e build in alluminio.',
  },
  {
    title: 'Logitech G733',
    slug: 'logitech-g733',
    category: 'Cuffie',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'Cuffie wireless LIGHTSPEED con fascia in tessuto elastico e cuscinetti soffici. RGB frontale e microfono con pop filter integrato. Autonomia 29 ore.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: 'Wireless LIGHTSPEED', battery_life: '29 ore', weight_g: 278, backlight: 'RGB frontale' },
    meta_title: 'Logitech G733 — Cuffie Wireless LIGHTSPEED',
    meta_description: 'Cuffie wireless con fascia tessuto, RGB e 29h autonomia. Gaming comodo tutto il giorno.',
  },
  {
    title: 'ASUS TUF Gaming H3',
    slug: 'asus-tuf-gaming-h3',
    category: 'Cuffie',
    price_current: p(35),
    price_original: null,
    currency: 'EUR',
    description: 'Cuffie cablate con driver da 53mm per bassi profondi e suono surround virtuale 7.1. Microfono unidirezionale con filtro antivento. Accesso al gaming premium a prezzo budget.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: '3.5mm', driver_size: '53mm', surround: '7.1 Virtuale', weight_g: 270 },
    meta_title: 'ASUS TUF Gaming H3 — Cuffie Gaming Budget',
    meta_description: 'Cuffie gaming con driver 53mm e surround 7.1. Il miglior ingresso nel gaming audio.',
  },
  {
    title: 'Razer BlackShark V2',
    slug: 'razer-blackshark-v2',
    category: 'Cuffie',
    price_current: p(65),
    price_original: null,
    currency: 'EUR',
    description: 'Cuffie da torneo con driver TriForce Titanium da 50mm per un suono ad alta risoluzione. Microfono HyperClear Cardioid con certificazione Esports. Il suono dei pro.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: '3.5mm + USB', driver: 'TriForce Titanium 50mm', microphone: 'HyperClear Cardioid', weight_g: 262 },
    meta_title: 'Razer BlackShark V2 — Cuffie da Torneo',
    meta_description: 'Driver TriForce 50mm e mic cardioid certificato. Le cuffie da torneo di Razer.',
  },

  // ══════════════════════════════════════
  //  STREAMING GEAR (15 prodotti)
  // ══════════════════════════════════════
  {
    title: 'Elgato Wave 3',
    slug: 'elgato-wave-3',
    category: 'Microfono',
    price_current: p(115),
    price_original: null,
    currency: 'EUR',
    description: 'Microfono USB cardioide con tecnologia Clipguard a doppio condensatore — non distorce mai, neanche ad alto volume. Mixer digitale integrato via Wave Link per controllo totale.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { polar_pattern: 'Cardioide', connectivity: 'USB-C', sample_rate: '96kHz/24bit', feature: 'Clipguard dual-capsule' },
    meta_title: 'Elgato Wave 3 — Microfono USB per Streaming',
    meta_description: 'Microfono USB 96kHz con Clipguard anti-distorsione. Qualità broadcast per streamer.',
  },
  {
    title: 'Blue Yeti',
    slug: 'blue-yeti',
    category: 'Microfono',
    price_current: p(85),
    price_original: null,
    currency: 'EUR',
    description: 'Il microfono USB più venduto al mondo con 3 capsule condenser e 4 pattern polari selezionabili. Plug & play su Mac e PC, perfetto per podcast, streaming e call.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { polar_patterns: 4, capsules: 3, connectivity: 'USB', sample_rate: '48kHz/16bit' },
    meta_title: 'Blue Yeti — Microfono USB Plug & Play',
    meta_description: 'Microfono USB con 4 pattern polari e 3 capsule. Il più venduto al mondo per streaming e podcast.',
  },
  {
    title: 'Rode NT-USB',
    slug: 'rode-nt-usb',
    category: 'Microfono',
    price_current: p(115),
    price_original: null,
    currency: 'EUR',
    description: 'Condensatore a studio collegato via USB. Suono caldo e naturale di qualità broadcast con pop filter magnetico incluso. Scelto da musicisti e content creator professionisti.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { polar_pattern: 'Cardioide', connectivity: 'USB-A/C', frequency_response: '20Hz–20kHz', includes: 'Pop filter + stand' },
    meta_title: 'Rode NT-USB — Microfono Condensatore Studio USB',
    meta_description: 'Qualità studio broadcast via USB. Pop filter magnetico incluso. Per creator professionisti.',
  },
  {
    title: 'Elgato Stream Deck MK2',
    slug: 'elgato-stream-deck-mk2',
    category: 'Stream Deck',
    price_current: p(125),
    price_original: null,
    currency: 'EUR',
    description: '15 tasti LCD personalizzabili per automatizzare tutto: scene OBS, clip Twitch, musica, luci smart. Plug & play con oltre 100 integrazioni. Il telecomando definitivo per streamer.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { keys: 15, display: 'LCD per-key', connectivity: 'USB-C', integrations: '100+' },
    meta_title: 'Elgato Stream Deck MK2 — 15 Tasti LCD per Streamer',
    meta_description: '15 tasti LCD programmabili per OBS, Twitch, Spotify e 100+ app. Lo strumento n.1 per streamer.',
  },
  {
    title: 'Elgato HD60 X',
    slug: 'elgato-hd60-x',
    category: 'Cattura Video',
    price_current: p(135),
    price_original: null,
    currency: 'EUR',
    description: 'Cattura e streama in 4K30 o 1080p60 HDR da PS5, Xbox Series X e Switch. Passthrough 4K60 a zero latenza — vedi su TV in alta qualità mentre registri per YouTube.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capture_max: '4K30 / 1080p60 HDR', passthrough: '4K60 HDR', connectivity: 'USB 3.0', compatible: 'PS5, Xbox, Switch' },
    meta_title: 'Elgato HD60 X — Scheda Cattura 4K per Console',
    meta_description: 'Cattura 4K30, passthrough 4K60 HDR. Compatibile con PS5, Xbox Series X e Switch.',
  },
  {
    title: 'Logitech StreamCam',
    slug: 'logitech-streamcam',
    category: 'Webcam',
    price_current: p(95),
    price_original: null,
    currency: 'EUR',
    description: 'Webcam 1080p60 con autofocus AI che traccia il tuo viso in automatico. USB-C, orientamento verticale per TikTok e Reels. Qualità professionale per stream e videocall.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { resolution: '1080p 60fps', autofocus: 'AI Face Tracking', connectivity: 'USB-C', orientation: 'Orizzontale + Verticale' },
    meta_title: 'Logitech StreamCam — Webcam 1080p60 USB-C',
    meta_description: 'Webcam 1080p60 con AI face tracking e supporto verticale. Perfetta per streaming e content creation.',
  },
  {
    title: 'Sony ZV-E10',
    slug: 'sony-zv-e10',
    category: 'Fotocamera',
    price_current: p(450),
    price_original: null,
    currency: 'EUR',
    description: 'Mirrorless APS-C con supporto microfoni direzionale dedicato per vlogging. Usata come webcam 4K via USB con zero configurazione. Il salto di qualità definitivo per il tuo canale.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { sensor: 'APS-C 24.2MP', video: '4K 30fps / 1080p 120fps', connectivity: 'USB Streaming + HDMI', mic_input: '3.5mm' },
    meta_title: 'Sony ZV-E10 — Mirrorless per Vlogging e Streaming',
    meta_description: 'Mirrorless APS-C 4K con bocca microfono dedicata. Usala come webcam 4K USB-C.',
  },
  {
    title: 'AVerMedia Live Gamer Mini',
    slug: 'avermedia-live-gamer-mini',
    category: 'Cattura Video',
    price_current: p(85),
    price_original: null,
    currency: 'EUR',
    description: 'Cattura 1080p60 HDR a latenza ultra-bassa in un form factor tascabile. Compatibile con PS5, Xbox e PC. Streaming simultaneo su Twitch e YouTube senza perdere un frame.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capture_max: '1080p60 HDR', passthrough: '1080p60 HDR', connectivity: 'USB 3.0', size: 'Mini tascabile' },
    meta_title: 'AVerMedia Live Gamer Mini — Cattura 1080p60 Tascabile',
    meta_description: 'Scheda cattura mini 1080p60 HDR. Streaming su Twitch e YouTube senza compromessi.',
  },
  {
    title: 'Neewer Ring Light 18"',
    slug: 'neewer-ring-light-18',
    category: 'Ring Light',
    price_current: p(55),
    price_original: null,
    currency: 'EUR',
    description: 'Ring light LED 18" da 55W con temperatura colore regolabile da 3200K a 5600K. Supporto universale per smartphone e fotocamere. Luce da studio professionale a casa tua.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '18 pollici', power: '55W', color_temp: '3200K–5600K', brightness_levels: 10 },
    meta_title: 'Neewer Ring Light 18" — Illuminazione Professionale',
    meta_description: 'Ring light LED 18" da 55W con temperatura regolabile. Luce broadcast per streaming e foto.',
  },
  {
    title: 'Elgato Key Light',
    slug: 'elgato-key-light',
    category: 'Illuminazione',
    price_current: p(145),
    price_original: null,
    currency: 'EUR',
    description: 'Luce LED professionale da 2500 lumen controllabile via Wi-Fi dall\'app o dallo Stream Deck. Temperatura da 2900K a 7000K per una luce sempre perfetta in ogni condizione.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { lumens: 2500, color_temp: '2900K–7000K', connectivity: 'Wi-Fi', control: 'App + Stream Deck' },
    meta_title: 'Elgato Key Light — Luce LED Professionale Wi-Fi',
    meta_description: '2500 lumen, temperatura regolabile, controllo via Wi-Fi. Illuminazione broadcast per ogni setup.',
  },
  {
    title: 'Rode PSA1 braccio microfono',
    slug: 'rode-psa1-braccio-microfono',
    category: 'Braccio Microfono',
    price_current: p(65),
    price_original: null,
    currency: 'EUR',
    description: 'Braccio professionale da scrivania con gestione cavi interna. Range di movimento 360° con molle di tensione regolabili. Compatibile con tutti i microfoni da studio.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { max_reach: '820mm', cable_routing: 'Interno', mount: 'Morsetto da scrivania', max_load: '1kg' },
    meta_title: 'Rode PSA1 — Braccio Microfono Professionale',
    meta_description: 'Braccio da scrivania 360° con cavi interni. Compatibile con tutti i mic da studio.',
  },
  {
    title: 'GoXLR Mini',
    slug: 'goxlr-mini',
    category: 'Mixer Audio',
    price_current: p(175),
    price_original: null,
    currency: 'EUR',
    description: 'Mixer USB compatto con 4 canali indipendenti e fader motorizzati. Effetti vocali in real-time, mute istantaneo e integrazione nativa con OBS e Twitch. Lo studio audio per streamer.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { channels: 4, faders: 'Motorizzati', effects: 'Vocali real-time', connectivity: 'USB + XLR' },
    meta_title: 'GoXLR Mini — Mixer USB per Streamer',
    meta_description: '4 canali, fader motorizzati ed effetti vocali. Il mixer definitivo per streaming professionale.',
  },
  {
    title: 'Focusrite Scarlett 2i2',
    slug: 'focusrite-scarlett-2i2',
    category: 'Audio Interface',
    price_current: p(125),
    price_original: null,
    currency: 'EUR',
    description: 'Interfaccia audio USB con 2 ingressi XLR/jack e preamp Air da studio. Latenza round-trip di 2.69ms per registrazioni clean e professionali. Lo standard per chi vuole qualità vera.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { inputs: '2x XLR/TRS', preamp: 'Focusrite Air', latency: '2.69ms', connectivity: 'USB-C' },
    meta_title: 'Focusrite Scarlett 2i2 — Interfaccia Audio USB',
    meta_description: '2 ingressi XLR, preamp Air, latenza 2.69ms. Lo standard per registrazione professionale.',
  },
  {
    title: 'HyperX QuadCast',
    slug: 'hyperx-quadcast',
    category: 'Microfono',
    price_current: p(95),
    price_original: null,
    currency: 'EUR',
    description: 'Microfono USB con 4 pattern polari selezionabili e LED indicatore di muto touch-sensitive. Sospensione elastica anti-vibrazione integrata. Pronto per lo streaming in 30 secondi.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { polar_patterns: 4, connectivity: 'USB', feature: 'Tap-to-mute LED', mount: 'Sospensione elastica' },
    meta_title: 'HyperX QuadCast — Microfono USB 4 Pattern Polari',
    meta_description: '4 pattern polari, tap-to-mute e sospensione anti-vibrazione. USB plug & play per streaming.',
  },
  {
    title: 'Shure MV7',
    slug: 'shure-mv7',
    category: 'Microfono',
    price_current: p(195),
    price_original: null,
    currency: 'EUR',
    description: 'Microfono dinamico ibrido USB/XLR ispirato al leggendario SM7B. Voce calda e naturale con reject del rumore ambientale superiore. Scelto da podcaster e streamer professionisti.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { polar_pattern: 'Cardioide dinamico', connectivity: 'USB + XLR', frequency_response: '50Hz–16kHz', inspired_by: 'Shure SM7B' },
    meta_title: 'Shure MV7 — Microfono Dinamico USB/XLR',
    meta_description: 'Dinamico ibrido USB/XLR ispirato all\'SM7B. Voce calda e professionale per podcast e streaming.',
  },

  // ══════════════════════════════════════
  //  MONITOR + DISPLAY (8 prodotti)
  // ══════════════════════════════════════
  {
    title: 'Samsung Odyssey G5',
    slug: 'samsung-odyssey-g5',
    category: 'Monitor 144hz',
    price_current: p(245),
    price_original: null,
    currency: 'EUR',
    description: 'Monitor gaming curvo 1000R da 27" con QHD 165Hz e 1ms. Curvatura immersiva che abbraccia il tuo campo visivo per sentire ogni frame. FreeSync Premium incluso.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '27"', resolution: '2560x1440', refresh_rate: '165Hz', response_time: '1ms', curvature: '1000R' },
    meta_title: 'Samsung Odyssey G5 — Monitor Curvo QHD 165Hz',
    meta_description: 'Monitor curvo 1000R QHD 165Hz. Immersione totale per gaming e streaming.',
  },
  {
    title: 'LG 27GP850',
    slug: 'lg-27gp850',
    category: 'Monitor 144hz',
    price_current: p(295),
    price_original: null,
    currency: 'EUR',
    description: 'Nano IPS 27" QHD con 165Hz e 1ms GtG. Copertura DCI-P3 98% per colori vividi e precisi anche nei contenuti HDR. La scelta unanime tra streamer e creator.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '27"', resolution: '2560x1440', panel: 'Nano IPS', refresh_rate: '165Hz', dci_p3: '98%' },
    meta_title: 'LG 27GP850 — Monitor Nano IPS QHD 165Hz',
    meta_description: 'Nano IPS QHD 165Hz con DCI-P3 98%. Il monitor preferito da streamer e creator.',
  },
  {
    title: 'ASUS TUF VG27AQ',
    slug: 'asus-tuf-vg27aq',
    category: 'Monitor 144hz',
    price_current: p(275),
    price_original: null,
    currency: 'EUR',
    description: 'IPS QHD 165Hz con ELMB Sync che elimina ghosting e tearing contemporaneamente. HDR400 e G-Sync compatible. Prestazioni da gaming senza compromessi su ogni gioco.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '27"', resolution: '2560x1440', panel: 'IPS', refresh_rate: '165Hz', feature: 'ELMB Sync + G-Sync' },
    meta_title: 'ASUS TUF VG27AQ — Monitor IPS QHD 165Hz G-Sync',
    meta_description: 'IPS QHD 165Hz con ELMB Sync e G-Sync. Zero ghosting e tearing per gaming competitivo.',
  },
  {
    title: 'AOC 24G2',
    slug: 'aoc-24g2',
    category: 'Monitor 144hz',
    price_current: p(145),
    price_original: null,
    currency: 'EUR',
    description: 'Monitor IPS FHD 144Hz da 24" con 1ms MPRT. FreeSync Premium e G-Sync compatible. Il punto di ingresso più accessibile per chi vuole 144Hz senza spendere troppo.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '24"', resolution: '1920x1080', panel: 'IPS', refresh_rate: '144Hz', response_time: '1ms MPRT' },
    meta_title: 'AOC 24G2 — Monitor Gaming IPS 144Hz Budget',
    meta_description: 'IPS FHD 144Hz a 24". Il miglior ingresso nel gaming monitor senza compromettere la qualità.',
  },
  {
    title: 'MSI Optix MAG274QRF',
    slug: 'msi-optix-mag274qrf',
    category: 'Monitor 144hz',
    price_current: p(275),
    price_original: null,
    currency: 'EUR',
    description: 'IPS QHD 165Hz con True Color certificato dal Calman e sRGB 99%. Hub USB integrato per tenere la scrivania in ordine. Qualità colore da studio nel form factor gaming.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '27"', resolution: '2560x1440', panel: 'IPS', refresh_rate: '165Hz', color_accuracy: 'Calman Verified' },
    meta_title: 'MSI Optix MAG274QRF — Monitor QHD Calman Verified',
    meta_description: 'QHD 165Hz con certificazione colore Calman e sRGB 99%. Per chi vuole gaming e creatività.',
  },
  {
    title: 'BenQ Zowie XL2546K',
    slug: 'benq-zowie-xl2546k',
    category: 'Monitor 144hz',
    price_current: p(345),
    price_original: null,
    currency: 'EUR',
    description: 'Monitor TN FHD 240Hz progettato esclusivamente per i tornei esport. DyAc+ elimina il motion blur durante le sparatorie. Scudo a visiera anti-distrazione incluso.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '24.5"', resolution: '1920x1080', panel: 'TN', refresh_rate: '240Hz', feature: 'DyAc+ motion blur reduction' },
    meta_title: 'BenQ Zowie XL2546K — Monitor Esport 240Hz',
    meta_description: 'TN 240Hz con DyAc+ per tornei esport. Il monitor degli atleti digitali professionisti.',
  },
  {
    title: 'LG 34GN850 Ultrawide',
    slug: 'lg-34gn850-ultrawide',
    category: 'Monitor',
    price_current: p(595),
    price_original: null,
    currency: 'EUR',
    description: 'Nano IPS curvo ultrawide 34" 21:9 con 160Hz. DCI-P3 98% per colori da cinema. Lo spazio di lavoro definitivo per streamer e creator che vogliono tutto in un\'unica schermata.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '34" 21:9', resolution: '3440x1440', panel: 'Nano IPS Curved', refresh_rate: '160Hz', dci_p3: '98%' },
    meta_title: 'LG 34GN850 Ultrawide — Monitor Curvo 34" 160Hz',
    meta_description: 'Nano IPS ultrawide curvo 34" 160Hz con DCI-P3 98%. Il setup definitivo per creator.',
  },
  {
    title: 'Gigabyte M27Q',
    slug: 'gigabyte-m27q',
    category: 'Monitor 144hz',
    price_current: p(235),
    price_original: null,
    currency: 'EUR',
    description: 'IPS QHD 170Hz con KVM switch integrato per controllare 2 PC con un unico set tastiera/mouse. HDR400 e copertura sRGB 92%. Produttività e gaming in un pannello unico.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '27"', resolution: '2560x1440', panel: 'IPS', refresh_rate: '170Hz', feature: 'KVM Switch integrato' },
    meta_title: 'Gigabyte M27Q — Monitor QHD 170Hz con KVM',
    meta_description: 'QHD 170Hz con KVM switch per 2 PC. Il monitor ideale per dual-setup e smartworking.',
  },

  // ══════════════════════════════════════
  //  ACCESSORI TECH (12 prodotti)
  // ══════════════════════════════════════
  {
    title: 'Docking Station USB-C Anker',
    slug: 'docking-station-usbc-anker',
    category: 'Accessori',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'Dock USB-C 13-in-1 con doppio display 4K, Ethernet Gigabit, 85W Power Delivery e lettore SD. Un solo cavo per trasformare il laptop in una workstation completa.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { ports: 13, displays: '2x 4K', ethernet: 'Gigabit', power_delivery: '85W', sd_reader: true },
    meta_title: 'Anker Docking Station USB-C — Hub 13-in-1',
    meta_description: 'Dock 13-in-1 con doppio 4K, Ethernet e 85W PD. Un cavo per tutto il tuo setup.',
  },
  {
    title: 'Hub USB-C 7-in-1',
    slug: 'hub-usbc-7in1',
    category: 'Accessori',
    price_current: p(28),
    price_original: null,
    currency: 'EUR',
    description: 'Hub compatto con HDMI 4K, 3xUSB-A 3.0, USB-C PD 100W, SD e microSD. Tascabile in alluminio per laptop, tablet e smartphone. Porta il tuo setup ovunque.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { ports: 7, hdmi: '4K@30Hz', usb_a: '3x USB-A 3.0', power_delivery: '100W', material: 'Alluminio' },
    meta_title: 'Hub USB-C 7-in-1 — Porta il Setup Ovunque',
    meta_description: 'Hub 7-in-1 tascabile con HDMI 4K e 100W PD. Connetti tutto da un unico punto.',
  },
  {
    title: 'SSD Esterno Samsung T7',
    slug: 'ssd-esterno-samsung-t7',
    category: 'SSD',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'SSD portatile NVMe con velocità fino a 1050 MB/s in lettura. Scocca in alluminio resistente agli urti. Perfetto per trasferire progetti video e backup istantanei.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capacity_tb: 1, read_speed: '1050 MB/s', write_speed: '1000 MB/s', connectivity: 'USB 3.2 Gen2', weight_g: 58 },
    meta_title: 'Samsung T7 — SSD Esterno NVMe 1050 MB/s',
    meta_description: 'SSD portatile NVMe 1050 MB/s in alluminio. Backup e trasferimenti in pochi secondi.',
  },
  {
    title: 'WD Black SN850X',
    slug: 'wd-black-sn850x',
    category: 'SSD',
    price_current: p(95),
    price_original: null,
    currency: 'EUR',
    description: 'SSD NVMe PCIe 4.0 interno da 1TB con velocità fino a 7300 MB/s. Ottimizzato per PS5 e PC gaming. Caricamenti istantanei e GameMode 2.0 per priorità automatica ai dati di gioco.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capacity_tb: 1, read_speed: '7300 MB/s', interface: 'PCIe 4.0 NVMe', ps5_compatible: true, feature: 'GameMode 2.0' },
    meta_title: 'WD Black SN850X — SSD NVMe PCIe 4.0 per Gaming',
    meta_description: 'NVMe PCIe 4.0 a 7300 MB/s con GameMode 2.0. Perfetto per PS5 e PC gaming ad alte prestazioni.',
  },
  {
    title: 'Corsair Vengeance RGB RAM',
    slug: 'corsair-vengeance-rgb-ram',
    category: 'RAM',
    price_current: p(65),
    price_original: null,
    currency: 'EUR',
    description: 'RAM DDR4 3200MHz 16GB (2x8GB) con illuminazione RGB dinamica sincronizzabile via iCUE. Dissipatore in alluminio a doppia faccia per temperature stabili anche sotto carico.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capacity_gb: 16, speed: '3200MHz DDR4', latency: 'CL16', rgb: true, heat_spreader: 'Alluminio doppio' },
    meta_title: 'Corsair Vengeance RGB — RAM 16GB DDR4 3200MHz',
    meta_description: 'RAM 16GB DDR4 3200MHz con RGB iCUE. Prestazioni stabili e look premium.',
  },
  {
    title: 'Kingston Fury Beast RAM',
    slug: 'kingston-fury-beast-ram',
    category: 'RAM',
    price_current: p(50),
    price_original: null,
    currency: 'EUR',
    description: 'RAM DDR4 3200MHz 16GB (2x8GB) plug-n-play con XMP automatico. Design low-profile che non occupa spazio per raffreddatori tower grandi. Affidabilità Kingston garantita.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { capacity_gb: 16, speed: '3200MHz DDR4', latency: 'CL16', profile: 'Low-profile', xmp: 'Auto XMP' },
    meta_title: 'Kingston Fury Beast — RAM 16GB DDR4 Low Profile',
    meta_description: 'RAM 16GB DDR4 3200MHz low-profile con XMP auto. Plug & play per qualsiasi build.',
  },
  {
    title: 'Logitech MX Master 3S',
    slug: 'logitech-mx-master-3s',
    category: 'Mouse',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'Il mouse per produttività più avanzato al mondo. Scroll MagSpeed elettromagnetico per scorrere 1000 righe in un secondo. Funziona su vetro e legno. Collega fino a 3 dispositivi.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: 'Bluetooth + USB Logi Bolt', scroll: 'MagSpeed Electromagnetic', devices: 3, battery_life: '70 giorni' },
    meta_title: 'Logitech MX Master 3S — Mouse Produttività Premium',
    meta_description: 'Scroll MagSpeed, multi-device e 70 giorni di batteria. Il mouse definitivo per la produttività.',
  },
  {
    title: 'Logitech MX Keys',
    slug: 'logitech-mx-keys',
    category: 'Tastiera',
    price_current: p(75),
    price_original: null,
    currency: 'EUR',
    description: 'Tastiera wireless ultra-silenziosa con tasti sferici a forma di punta delle dita. Retroilluminazione intelligente che si attiva solo quando le mani si avvicinano. Connetti 3 dispositivi.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { connectivity: 'Bluetooth + USB Bolt', backlight: 'Smart proximity', devices: 3, battery_life: '10 giorni con backlight' },
    meta_title: 'Logitech MX Keys — Tastiera Wireless Multi-Device',
    meta_description: 'Tasti sferici, backlight smart e multi-device. La tastiera wireless per chi lavora su più schermi.',
  },
  {
    title: 'Secretlab Titan Evo',
    slug: 'secretlab-titan-evo',
    category: 'Sedia Gaming',
    price_current: p(345),
    price_original: null,
    currency: 'EUR',
    description: 'Sedia gaming con lombare magnetica 4D integrata e braccioli 4D ultra-regolabili. Seduta a memoria di forma da 12cm. Certificata BIFMA e SGS per uso intensivo fino a 180kg.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { lumbar: 'Magnetico 4D', armrests: '4D', foam_density: '12cm memory foam', max_weight_kg: 180, certification: 'BIFMA + SGS' },
    meta_title: 'Secretlab Titan Evo — Sedia Gaming Premium',
    meta_description: 'Lombare magnetica 4D, braccioli 4D e foam memory. La sedia gaming definitiva certificata BIFMA.',
  },
  {
    title: 'Supporto Monitor VESA Doppio',
    slug: 'supporto-monitor-vesa-doppio',
    category: 'Accessori',
    price_current: p(45),
    price_original: null,
    currency: 'EUR',
    description: 'Braccio doppio per due monitor da scrivania con molle a gas per regolazione senza sforzo. VESA 75/100mm, porta fino a 9kg per braccio. Libera la scrivania e crea il dual-setup perfetto.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { monitors: 2, vesa: '75x75 / 100x100mm', max_weight_kg: 9, adjustment: 'Molle a gas' },
    meta_title: 'Supporto VESA Doppio — Braccio per 2 Monitor',
    meta_description: 'Braccio dual monitor con molle a gas. Libera la scrivania e crea il setup perfetto.',
  },
  {
    title: 'Supporto Microfono Low-Profile',
    slug: 'supporto-microfono-low-profile',
    category: 'Accessori',
    price_current: p(22),
    price_original: null,
    currency: 'EUR',
    description: 'Supporto da scrivania compatto con filetto 5/8" e adattatore 3/8". Antivibrazione con base in gomma. Tenuto basso per non ostacolare la webcam durante le sessioni live.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { thread: '5/8" + 3/8" adattatore', base: 'Antivibrazione gomma', height_cm: 15, compatible: 'Tutti i microfoni da studio' },
    meta_title: 'Supporto Microfono Low-Profile — Compatto per Streaming',
    meta_description: 'Supporto microfono da scrivania antivibrazione. Non ostruisce la webcam durante lo streaming.',
  },
  {
    title: 'Tappetino Mouse XXL RGB',
    slug: 'tappetino-mouse-xxl-rgb',
    category: 'Mousepad',
    price_current: p(28),
    price_original: null,
    currency: 'EUR',
    description: 'Tappetino desk-size XXL 900x400mm con bordi cuciti e illuminazione RGB a 14 effetti. Base antiscivolo spessa 4mm. Copre tutta la scrivania per un setup coeso e luminoso.',
    image_url: PLACEHOLDER,
    is_direct_sell: true,
    specs: { size: '900x400x4mm', rgb_effects: 14, edge: 'Cucito antisfrangitura', base: 'Antiscivolo gomma' },
    meta_title: 'Tappetino Mouse XXL RGB — 900x400mm con LED',
    meta_description: 'Mousepad desk-size XXL 900x400mm con 14 effetti RGB. Copre tutta la scrivania per un setup perfetto.',
  },
]

async function seed() {
  console.log('🚀 Avvio seed catalogo — 50 prodotti...\n')

  // Pulizia preventiva (seed idempotente)
  const { error: deleteError } = await db
    .from('products')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000')

  if (deleteError) {
    console.error('⚠️  Errore pulizia:', deleteError.message)
  } else {
    console.log('🗑️  Tabella prodotti svuotata\n')
  }

  // Insert a blocchi da 10 per evitare timeout
  const CHUNK = 10
  let inserted = 0

  for (let i = 0; i < products.length; i += CHUNK) {
    const chunk = products.slice(i, i + CHUNK)
    const { data, error } = await db
      .from('products')
      .insert(chunk)
      .select('id, title, price_current')

    if (error) {
      console.error(`❌ Errore blocco ${i / CHUNK + 1}:`, error.message)
    } else {
      inserted += data.length
      data.forEach((p) =>
        console.log(`  ✅ ${p.title} — €${p.price_current}`)
      )
    }
  }

  console.log(`\n✨ Seed completato! ${inserted}/${products.length} prodotti inseriti.`)
}

seed().catch((err) => {
  console.error('Errore fatale:', err)
  process.exit(1)
})
